kind = "DojoModel"
class_hash = "0x5a184e5d79cb412daff88b15fc262f51148b8236d0e88c140af0004f0ef9417"
original_class_hash = "0x5a184e5d79cb412daff88b15fc262f51148b8236d0e88c140af0004f0ef9417"
abi = "manifests/dev/base/abis/models/goblin_dungeon-Player-25b86644.json"
tag = "goblin_dungeon-Player"
manifest_name = "goblin_dungeon-Player-25b86644"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "team_id"
type = "u32"
key = false

[[members]]
name = "name"
type = "felt252"
key = false
