kind = "DojoModel"
class_hash = "0x4963d1f53dc28627702f3eaf2d4bf1fed2bb0dfebaa54ffa54f75f5cd3aa313"
original_class_hash = "0x4963d1f53dc28627702f3eaf2d4bf1fed2bb0dfebaa54ffa54f75f5cd3aa313"
abi = "manifests/dev/base/abis/models/goblin_dungeon-Mob-57fe6720.json"
tag = "goblin_dungeon-Mob"
qualified_path = "rpg::models::index::mob"
manifest_name = "goblin_dungeon-Mob-57fe6720"

[[members]]
name = "dungeon_id"
type = "u32"
key = true

[[members]]
name = "team_id"
type = "u32"
key = true

[[members]]
name = "index"
type = "u8"
key = true

[[members]]
name = "class"
type = "u8"
key = false

[[members]]
name = "element"
type = "u8"
key = false

[[members]]
name = "spell"
type = "u8"
key = false

[[members]]
name = "health"
type = "u8"
key = false

[[members]]
name = "shield"
type = "u8"
key = false

[[members]]
name = "stun"
type = "u8"
key = false

[[members]]
name = "multiplier"
type = "u8"
key = false
