kind = "DojoModel"
class_hash = "0x5a4bf296f23729f0f66d5a35eb86e8be5ce862389f483166b2d29a2ac82703"
original_class_hash = "0x5a4bf296f23729f0f66d5a35eb86e8be5ce862389f483166b2d29a2ac82703"
abi = "manifests/dev/base/abis/models/grimscape-Team-2008b6e4.json"
tag = "grimscape-Team"
qualified_path = "grimscape::models::index::team"
manifest_name = "grimscape-Team-2008b6e4"

[[members]]
name = "dungeon_id"
type = "u32"
key = true

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "x"
type = "i32"
key = false

[[members]]
name = "y"
type = "i32"
key = false

[[members]]
name = "dead"
type = "bool"
key = false

[[members]]
name = "deck"
type = "u64"
key = false

[[members]]
name = "spells"
type = "u16"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false

[[members]]
name = "player_id"
type = "felt252"
key = false
