tag = "grimscape-actions"
writes = [
    "grimscape-Player",
    "grimscape-Factory",
    "grimscape-Dungeon",
    "grimscape-Room",
    "grimscape-Team",
    "grimscape-Mob",
    "grimscape-Challenge",
]
init_calldata = []
