[world]
name = "Gimscape"
description = "A fully onchain RPG game."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "grimscape"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/starter-rpg"
telegram = "https://t.me/dojoengine"

[namespace]
default = "grimscape"

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x2d183f81086e5cbff082e3a827720f2fe0c838195295d59eb437d114c37a0e3"
private_key = "0x4767f45a89c834665441f166f72169586b0d96014708649832fc2c174d2af97"
