kind = "DojoContract"
class_hash = "0x3e20f5d3376cee2c26992d705ee557672ed0f4c4a4a01e8069e66db9f155ae4"
original_class_hash = "0x3e20f5d3376cee2c26992d705ee557672ed0f4c4a4a01e8069e66db9f155ae4"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/grimscape-actions-bc726048.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-actions"
systems = [
    "signup",
    "rename",
    "spawn",
    "move",
    "attack",
    "hire",
    "pickup",
    "burn",
    "heal",
]
manifest_name = "grimscape-actions-bc726048"
