kind = "DojoContract"
class_hash = "0x4a3ae8338584692bfa463a526128e3af1de38b5ab98e8c372a1317af1a55486"
original_class_hash = "0x4a3ae8338584692bfa463a526128e3af1de38b5ab98e8c372a1317af1a55486"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/grimscape-actions-18ec7a89.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-actions"
systems = [
    "signup",
    "rename",
    "spawn",
    "move",
    "attack",
    "hire",
    "pickup",
    "burn",
    "heal",
]
manifest_name = "grimscape-actions-18ec7a89"
