kind = "DojoContract"
class_hash = "0x558aa712ade8cb884ddd6c820bf891bd74bfd8731acd81d6a70d5622e92b048"
original_class_hash = "0x558aa712ade8cb884ddd6c820bf891bd74bfd8731acd81d6a70d5622e92b048"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/goblin_dungeon-actions-bc726048.json"
reads = []
writes = []
init_calldata = []
tag = "goblin_dungeon-actions"
systems = [
    "signup",
    "rename",
    "spawn",
    "move",
    "attack",
]
manifest_name = "goblin_dungeon-actions-bc726048"
