kind = "DojoContract"
class_hash = "0x177e70d2579ef40d590af1781db403e3d72b410fca655635c6582aa0f0a2edc"
original_class_hash = "0x177e70d2579ef40d590af1781db403e3d72b410fca655635c6582aa0f0a2edc"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/goblin_dungeon-actions-bc726048.json"
reads = []
writes = []
init_calldata = []
tag = "goblin_dungeon-actions"
systems = [
    "signup",
    "rename",
    "spawn",
    "move",
    "attack",
]
manifest_name = "goblin_dungeon-actions-bc726048"
