kind = "DojoContract"
class_hash = "0x537e9836bdf6969e4980a71ebac1c0143781816ba51229eece52448725507d3"
original_class_hash = "0x537e9836bdf6969e4980a71ebac1c0143781816ba51229eece52448725507d3"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/grimscape-actions-18ec7a89.json"
reads = []
writes = []
init_calldata = []
tag = "grimscape-actions"
systems = [
    "signup",
    "rename",
    "spawn",
    "move",
    "attack",
    "hire",
    "pickup",
    "burn",
    "heal",
]
manifest_name = "grimscape-actions-18ec7a89"
